set(KinectSDK2_FOUND OFF CACHE BOOL "Kinect 2.x SDK found")
set(KINECTSDK20_DIR "NOT FOUND" CACHE PATH "Kinect 2.x SDK path")
if(WIN32)
    if(EXISTS $ENV{KINECTSDK20_DIR})
        message(KINECT_FOUND)
        set(KinectSDK2_FOUND ON CACHE BOOL "Kinect 2.x SDK found" FORCE)
        set(KinectSDK2_DIR $ENV{KinectSDK2_DIR} CACHE PATH "Kinect 2.x SDK path" FORCE)

        if(EXISTS $ENV{KINECTSDK20_DIR}/inc)
            set(KinectSDK2_INCLUDE_DIRS $ENV{KINECTSDK20_DIR}/inc CACHE PATH "Kinect v2 inclue path" FORCE)
            message(KINECT_INC_FOUND)
        endif()
        if(EXISTS $ENV{KINECTSDK20_DIR}/lib/x86/)
            set(KinectSDK2_LIBRARY_DIRS $ENV{KINECTSDK20_DIR}/lib/x86/ CACHE PATH "Kinect v2 library dirs" FORCE)
            message(KINECT_LIB_DIR_FOUND)
        endif()
        if(EXISTS $ENV{KINECTSDK20_DIR}/lib/x86/Kinect20.lib)
            set(KinectSDK2_LIBRARIES $ENV{KINECTSDK20_DIR}/lib/x86/Kinect20.lib CACHE PATH "Kinect v2 library path" FORCE)
            message(KINECT_LIB_FOUND)
        endif()
    endif()
else()
endif()
