if(AR STREQUAL "x64" OR AR STREQUAL "x86")
    message("NOTICE [KinectUtils]: Using libraries for ${AR}")
else()
    set(AR x86)
    message("NOTICE [KinectUtils]: Architecture is not set. Defaulting to x86")
endif()

set(KinectSDK2_FOUND OFF CACHE BOOL "Kinect 2.x SDK found")
set(KINECTSDK20_DIR "NOT FOUND" CACHE PATH "Kinect 2.x SDK path")
if(WIN32)
    if(EXISTS $ENV{KINECTSDK20_DIR})
        set(KinectSDK2_FOUND ON CACHE BOOL "Kinect 2.x SDK found" FORCE)
        set(KinectSDK2_DIR $ENV{KinectSDK2_DIR} CACHE PATH "Kinect 2.x SDK path" FORCE)

        if(EXISTS $ENV{KINECTSDK20_DIR}/inc)
            set(KinectSDK2_INCLUDE_DIRS $ENV{KINECTSDK20_DIR}/inc CACHE PATH "Kinect v2 inclue path" FORCE)
        else()
            message("ERROR [KinectUtils]: Kinect includes files cannot be found!")
        endif()
        if(EXISTS $ENV{KINECTSDK20_DIR}/lib/${AR}/)
            set(KinectSDK2_LIBRARY_DIRS $ENV{KINECTSDK20_DIR}/lib/${AR}/ CACHE PATH "Kinect v2 library dirs" FORCE)
        else()
            message("ERROR [KinectUtils]: Kinect ${AR} library dir cannot be found")
        endif()
        if(EXISTS $ENV{KINECTSDK20_DIR}/lib/${AR}/Kinect20.lib)
            set(KinectSDK2_LIBRARIES $ENV{KINECTSDK20_DIR}/lib/${AR}/Kinect20.lib CACHE PATH "Kinect v2 library path" FORCE)
        else()
            message("ERROR [KinectUtils]: Kinect ${AR} library file cannot be found")
        endif()
    endif()
else()
endif()
